kind: pipeline
type: docker
name: registerToContainer


steps:
  - name: reverso  
    image: plugins/docker
    settings:
      repo: registry.digitalocean.com/sebathi/reverso
      registry: registry.digitalocean.com/sebathi
      dockerfile: ./Dockerfile
      tags: 
        - 'latest'
      config: 
        from_secret: do_registry_config
